### ISSUE TITLE
enable ldap login

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/pyramid-phoenix#17]

**Comment by Kruecke** [comment]
I'm very interested in this feature. Is there any development branch for this yet? I would gladly participate in development (although I'm not too deep into Phoenix yet).

**Comment by cehbrecht** [comment]
ldap login is just on my todo list yet. 

Currently i'm using authomatic (http://peterhudec.github.io/authomatic/index.html) for openid login. It has also implementations for oauth ... but haven't seen ldap. There is also a pyramid_ldap module which i have not tried yet: http://docs.pylonsproject.org/projects/pyramid-ldap/en/latest/

What are your plans to use WPS and Phoenix for?

If you like to work on this you could start with a fork from the master branch.

**Comment by Kruecke** [comment]
Thanks for the links!

Unfortunately I'm not quite certain about future usages yet. I've just started out as a student assistant at KIT and I'm an IT student which means that (unlike my boss) I've basically no clue about all that climate stuff.

My first goal is to make the service usable with our local LDAP environment and to dig into the WPS Emu examples. I assume that I'll use the platform to implement and provide own WPSs later on.

I think I will go ahead and fork the master branch as you recommended. :-)

**Comment by cehbrecht** [comment]
i've moved the ldap requirements (from  bootstrap) to `requirements.sh` in pyramid. When running `make sysinstall` these requirements will be installed.

**Comment by Kruecke** [comment]
Yes, this looks like a better place for these dependencies. Thanks!

**Comment by Kruecke** [comment]
Done by merging #31.
