### ISSUE TITLE
Not all templates are overridable

### ISSUE THREAD

**Issue by tommygod3** [bird-house/pyramid-phoenix#202]
Some templates and static files in Phoenix use asset specifications, because they show the package they come from they an be easily overridden.
Example of asset specification in Phoenix:
https://github.com/bird-house/pyramid-phoenix/blob/efc0e26cfdfc5b900f2ae0cac57d3d2610d19514/phoenix/panels.py#L9
Example of overriding template taking advantage of asset specification:
```
config.override_asset(
    to_override="phoenix:templates/panels/navbar.pt",
    override_with="my_templates_package:templates/panels/navbar.pt"
)
```
However not all assets in Phoenix do use asset specification, some are relative paths such as:
https://github.com/bird-house/pyramid-phoenix/blob/efc0e26cfdfc5b900f2ae0cac57d3d2610d19514/phoenix/processes/views/list.py#L25
This stops those assets from being easily overridden and therefore I suggest that all asset relative paths be switched to asset specifications.
I am happy to make this PR.

**Comment by cehbrecht** [comment]
A PR is welcome :)
