### ISSUE TITLE
Error while logging in as admin

### ISSUE THREAD

**Issue by tommygod3** [bird-house/pyramid-phoenix#206]
This line in the twitcher client sends two arguments to the function generate_token:
https://github.com/bird-house/pyramid-phoenix/blob/014040ba2f443f19e7028ce90970a6332920079f/phoenix/twitcherclient.py#L52

Recently twitcher was changed and this function now only accepts one argument:
 https://github.com/bird-house/twitcher/blob/511739de930f3eaf32dcb3ebff5146c1f76f8018/twitcher/client.py#L64

I will submit a PR removing this second argument `data`

**Comment by tommygod3** [comment]
It seems that the new patch of Twitcher requires more than just this small change to work. Until this compatibility is fixed I will use Twitcher 0.4.0

**Comment by cehbrecht** [comment]
@tommygod3 As long the Twitcher 0.4.0 is working I would also keep it. Twitcher is currently refactored to support oauth. When this is stable we can adapt the Phoenix code to the "new" twitcher.

**Comment by cehbrecht** [comment]
@tommygod3 I have added PR #208 to pin twitcher 0.4.0.
