### ISSUE TITLE
IPython requires 'notebook' folder in docs/

### ISSUE THREAD

**Issue by Kruecke** [bird-house/pyramid-phoenix#22]
The title says it all. After a fresh installation of malleefowl and pyramid, followed the typical `make start`, IPython will die a few times before Supervisor gives up on retrying to bring up the process. 

The reason of the problem is shown in the log file:
```
[fklemme@null-080027f84ec6 ~]$ tail .conda/envs/birdhouse/var/log/supervisor/ipython-stdout---supervisor-djeztv.log 
supervisor: couldn't chdir to /home/fklemme/pyramid-phoenix/docs/notebook: ENOENT
supervisor: child process was not spawned
supervisor: couldn't chdir to /home/fklemme/pyramid-phoenix/docs/notebook: ENOENT
supervisor: child process was not spawned
supervisor: couldn't chdir to /home/fklemme/pyramid-phoenix/docs/notebook: ENOENT
supervisor: child process was not spawned
```
The workaround is quite easy:
```
mkdir -p ~/pyramid-phoenix/docs/notebook
```
Tested on CentOS 6, but likely to affect other platforms as well.

**Comment by cehbrecht** [comment]
thanks for looking at this :) 

i've fixed the buildout setup for ipython in `config/ipython.cfg`. The notebook folder will be created now in `.conda/envs/birdhouse/tmp/notebooks`.

ipython together with phoenix was used for a demo ... it's not really finished and i'm not sure if i will keep it this way.
