### ISSUE TITLE
Schemas as POST forms

### ISSUE THREAD

**Issue by Kruecke** [bird-house/pyramid-phoenix#27]
I currently merged my ldap fork with your upstream changes. First of all, phoenix looks great! Good work! :-)
I've moved my login template as a schema to `phoenix/schema/__init__.py`, basically just by copying `ESGFLoginSchema`. It works fine, but all arguments are passed as GET values. Not so great, as one of the arguments is a password.
```
http://localhost:8081/account/ldap?username=admin&password=supergeheim
```
Do you have any idea how I can change that to be a POST form? Otherwise is there any documentary you can refer me to?

**Comment by cehbrecht** [comment]
oooh .... i made quite some changes ... hopefully merging was not a pain. I didn't see that you had already some commits. Maybe you could work on your own branch  "krueckedev" or so  (no fork) so that i can merge your changes from time to time ... ? I will send you an invitation and you can create "your" dev branch if you like.

Are you using the pyramid_ldap module? Usually i use deform/colander for forms ... so i don't need to care by myself ... and deform should use post requests ...

http://docs.pylonsproject.org/projects/deform/en/latest/index.html

**Comment by Kruecke** [comment]
> oooh .... i made quite some changes ... hopefully merging was not a pain.
Yeah, you've changed a lot. Considering the fact that these tools are always having some problems following changes in renamed/moved files, merging was okay. ;-)

> Maybe you could work on your own branch "krueckedev" or so (no fork) so that i can merge your changes from time to time ... ?
That would be awesome! Especially because I'd be able to use some of Githubs features like commenting a line of code and things like that. That would be quite helpful as I sometimes stumble upon some code where I'm unsure what it is for, if it's a bug or if it's supposed to be the way it is.

> Are you using the pyramid_ldap module? Usually i use deform/colander for forms ... so i don't need to care by myself ... and deform should use post requests ...
I am. And I think I'm using deform/colander just like you. But maybe I'm mistaken somewhere...

Btw: I used to be a C++ (mostly cli) programmer and I'm still quite new to python and all this web programming. I took some time to read python tutorials and worked through the pyramid quick tutorial (http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/index.html), so I think I have a very basic idea about the structure of pyramid and phoenix; that's where I stand now. I might come up with some questions, especially about how a decent set up for testing and debugging could look like. Would it be okay for you to bother you with such questions? If yes, is there a preferred way? 'Issues' might not be the right place for general questions, I guess.

**Comment by cehbrecht** [comment]
you can send me an email ehbrecht at dkrz.de. Just feel free to ask :)

There is also a demo for deform forms:

https://github.com/Pylons/deformdemo

**Comment by Kruecke** [comment]
I finally "fixed" my problem. The form has always been correct, but [this](https://github.com/bird-house/pyramid-phoenix/blob/master/phoenix/views/account.py#L61) redirection caused the trouble:
```
    def process_form(self, form, protocol):
# ...
            appstruct = form.validate(controls)
# ...
            return HTTPFound(location=self.request.route_path('account_openid', _query=appstruct.items()))
```
Here, the POST items get converted to an URL to be redirected to the view that finally handles the values. This redirection seems to be very redundant (as far as I can tell) so I just striped it for ldap in my development branch. Have a look at commit 070660d059721f8042e0af41b11f6c1063384f14 to see what has changed.

Maybe this change should be applied to OpenID as well as it spares some code and even gives some performance improvement.

**Comment by Kruecke** [comment]
OpenID redirect also uses very long URLs, like this one: `http://centos-vm:8081/account/openid?realm=realm&janrain_nonce=2015-06-19T14%3A18%3A18ZUobboU&openid.claimed_id=http%3A%2F%2Fflorianklemme.de%2F&openid.identity=https%3A%2F%2Fopenid.stackexchange.com%2Fuser%2Fe982b8f3-e93f-446e-8f69-b715116147c6&openid.sig=4t9ubgMtPEh9GU%2BpqoRcYV7i%2BU0%3D&openid.signed=claimed_id%2Cidentity%2Cassoc_handle%2Cop_endpoint%2Creturn_to%2Cresponse_nonce%2Cns.sreg%2Csreg.email%2Csreg.fullname%2Cns.alias3%2Calias3.mode%2Calias3.type.alias1%2Calias3.value.alias1%2Calias3.type.alias2%2Calias3.value.alias2&openid.assoc_handle=tVxf%21IAAAAPEYudrm54BLgVWZHQzfdDj_lS9s6bl9o8Pnx9YGcRCfMQAAAAGmwQ2k40al0d2qQw6KgKO4JJQOCIg1M7YWLdz6tTHouLluQ9zlHUwDMiT2oV2-5Rk&openid.op_endpoint=https%3A%2F%2Fopenid.stackexchange.com%2Fopenid%2Fprovider&openid.return_to=http%3A%2F%2Fcentos-vm%3A8081%2Faccount%2Fopenid%3Frealm%3Drealm%26janrain_nonce%3D2015-06-19T14%253A18%253A18ZUobboU&openid.response_nonce=2015-06-19T14%3A18%3A21Z1BTP12nb&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.sreg.email=mail%40florianklemme.de&openid.sreg.fullname=Florian%20Klemme&openid.ns.alias3=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.alias3.mode=fetch_response&openid.alias3.type.alias1=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.alias3.value.alias1=mail%40florianklemme.de&openid.alias3.type.alias2=http%3A%2F%2Faxschema.org%2FnamePerson&openid.alias3.value.alias2=Florian%20Klemme` (1490 characters long!)

I wouldn't wonder if this causes some trouble some day. Just to keep in mind.
