### ISSUE TITLE
Wrong redirect from http to https.

### ISSUE THREAD

**Issue by Kruecke** [bird-house/pyramid-phoenix#33]
When I connect to `http://phoenix:8081`, I'll be getting redirected to `https://localhost:8443`. (The host name has been omitted and replaced by `localhost`.)

**Comment by cehbrecht** [comment]
hopefully this happens only if your browser is opened on the same "localhost". Setting the hostname works on my demo server for external use. The nginx config looks fine:

```bash
$ less ~/.conda/envs/birdhouse/etc/nginx/conf.d/phoenix.conf
```

**Comment by Kruecke** [comment]
It says just `localhost` in my configuration.
Doesn't it fetch the system hostname during installation?

What is `${settings:hostname}` referring to?
```
[phoenix_nginx]
...
hostname =  ${settings:hostname}
```

Or is `localhost` just hardcoded in [birdhousebuilder.recipe.nginx](https://github.com/bird-house/birdhousebuilder.recipe.nginx/blob/master/birdhousebuilder/recipe/nginx/__init__.py)?
```
self.options['hostname'] = self.options.get('hostname', 'localhost')
```

**Comment by cehbrecht** [comment]
it doesn't take the system hostname automatically. You need to set the hostname in custom.cfg (will overwrite settings:hostname). By default the hostname is `localhost`.

**Comment by Kruecke** [comment]
Stupid me, I should have seen that option as it is already set in `custom.cfg.example`.
Okay, that's fine then, I guess.
