### ISSUE TITLE
LDAP: Test if system packages can be stripped.

### ISSUE THREAD

**Issue by Kruecke** [bird-house/pyramid-phoenix#35]
I still haven't tested this one: https://github.com/bird-house/pyramid-phoenix/pull/31#issuecomment-114187700

If that test works, we have to check how to make the build work using the Makefile.

**Comment by Kruecke** [comment]
> There is `python-ldap` on conda. I've added it to the conda packages in `config/phoenix.cfg`. You might give it a try so that we can remove the ldap system packages?

You've been right. If you install `python-ldap` via conda *before* running `make`, you can omit anything from `requirements.sh` indeed.
```
$ source activate birdhouse
$ conda install python-ldap
$ source deactivate birdhouse
$ make -C pyramid-phoenix
```

> Unfortunately buildout did not install conda packages in the correct order ... first conda ... then phoenix.

@cehbrecht: Can you fix that? I don't know how to do this.

**Comment by cehbrecht** [comment]
i've added `python-ldap` to `config/phoenix.cfg` in the conda section and removed the ldap packages from `requirements.sh`

**Comment by Kruecke** [comment]
Travis seems to be happy with this change. :-)

**Comment by Kruecke** [comment]
@cehbrecht Wait, what? How did you fixed the "wrong order" thing? Did you change anything but deleting the lines in `requirements.sh`? The change to `config/phoenix.cfg` is already three weeks old.

**Comment by cehbrecht** [comment]
buildout did this time that right thing ... first install conda then the rest. I didn't change the buildout ;) 

to make sure that conda packages are always installed first i would introduce an additional buildout step ... maybe putting conda requirements into a `reqiurement.cfg` buildout config or having a common requirement section ... but the build steps need to be changed in the makefile ...
