### ISSUE TITLE
Already logged in - on a fresh installation.

### ISSUE THREAD

**Issue by fklemme** [bird-house/pyramid-phoenix#36]
While testing, I experienced this strange artefact quite a few times. When I've been logged in into Phoenix and then completely purge and reinstall my Phoenix installation, I'm still logged in (as nobody?) into Phoenix.

![still_logged_in](https://cloud.githubusercontent.com/assets/5053254/8524806/a04b875c-23fd-11e5-8c9b-ef0919fd8cef.png)

I always thought I just missed some files when I deleted the local installation, but I also experienced this behaviour with a virtual host which has been completely reinstalled (including partitions and operating system). Just the hostname remained the same after the host has been reinstalled again.

I haven't tagged this one as a bug, as it doesn't really seem to cause any problems and it's just very unlikely to be ever seen in a relevant, non-developement system. I just wanted to post this issue to have it in mind - maybe it becomes relevant sometime.

**Comment by cehbrecht** [comment]
logged-in status depends on your browser session ... phoenix uses beaker (https://pypi.python.org/pypi/pyramid_beaker) which caches session states on the filesystem ...
