### ISSUE TITLE
Wizard gets stuck on "Choose Input Parameter"

### ISSUE THREAD

**Issue by fklemme** [bird-house/pyramid-phoenix#37]
When I test the wizard with Emu, I always get stuck on this page.

![input_fail](https://cloud.githubusercontent.com/assets/5053254/8526932/f10941f0-2409-11e5-8205-a4e1579925ab.png)

**Comment by cehbrecht** [comment]
the wizard currently only accepts input parameters for netcdf mime-type. Unfortunately Emu does not have such a process ;) This is not obvious in the wizard ...
