### ISSUE TITLE
Length restriction on input sequences

### ISSUE THREAD

**Issue by Kruecke** [bird-house/pyramid-phoenix#52]
It seems to be implemented, but I can't see it working.
https://github.com/bird-house/pyramid-phoenix/blob/master/phoenix/schema/wps.py#L138

**Comment by Kruecke** [comment]
I just realized that my case might not be handled in that part of the code. Here is my PyWPS node:
```
self.timeBegin = self.addLiteralInput(
            identifier = 'timeBegin',
            title = 'Begin date',
            abstract = 'Begin date (DD.MM.YYYY)',
            type = date, # TODO: This doesn't seem to be enough to prevent illegal dates.
            minOccurs = 0,
            maxOccurs = 1, # This seems to be ignore by the phoenix web interface.
            )
```

**Comment by cehbrecht** [comment]
the latest emu (pywps-4) has an in-out process with max_occurs=2:

https://github.com/bird-house/emu/blob/master/emu/processes/wps_inout.py#L47

works with the latest phoenix:

![more-than-two](https://cloud.githubusercontent.com/assets/4965260/21141524/03641f0a-c13e-11e6-85aa-7faf528cdd3b.png)
