### ISSUE TITLE
wizard transports only default settings for literal inputs

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/pyramid-phoenix#66]
argument transportation works fine while submitting jobs via 'processes' while jobs submitted with 'wizard' receiving only the default settings.

**Comment by cehbrecht** [comment]
> 'wizard' receiving only the default settings. 

this means that you can not change the literal inputs for the submitted process?

**Comment by nilshempelmann** [comment]
What ever you set in the GUI will be overwritten by the default setting.

**Comment by nkadygrov** [comment]
I remember, that I fix it by setting for inputs:
minOccurs=1,
maxOccurs=1
in wps process. for example.

**Comment by cehbrecht** [comment]
@nilshempelmann 
probably it does not happen with every process. Which process should i check?

**Comment by nilshempelmann** [comment]
Happens with SDM - process
And as far as I know also subset_countries

**Comment by cehbrecht** [comment]
there was an error in wizard template. seams to work now.

update phoenix (master) and flyingpigeon (master).
