### ISSUE TITLE
accessing features after installation

### ISSUE THREAD

**Issue by seckmag** [bird-house/pyramid-phoenix#86]
Hi ,

I have installed pyramid-phoenix on my VM . However there is nothing else i am allowed to do after that.
How do i get access to the different features of phoenix .It is said that an authorization should be granted to me but i don't know where to ask for that .
I have already created an account on esgf openid dkrz.
thank you

**Comment by nilshempelmann** [comment]
What are you trying to do? :-)
Gues that easier to be discussed in the chat: 
https://gitter.im/bird-house/birdhouse
